-- Create blocked_users table for user blocking feature
create table if not exists blocked_users (
  id bigint generated by default as identity primary key,
  blocked_by uuid references auth.users(id) not null,
  blocked_user uuid references auth.users(id) not null,
  created_at timestamptz default now(),
  unique(blocked_by, blocked_user)
);

-- Enable Row Level Security
alter table blocked_users enable row level security;

-- Policy: Users can see their own blocked users
create policy "Users can view their own blocked users"
  on blocked_users for select
  using (auth.uid() = blocked_by);

-- Policy: Users can block other users
create policy "Users can block other users"
  on blocked_users for insert
  with check (auth.uid() = blocked_by);

-- Policy: Users can unblock users
create policy "Users can unblock users"
  on blocked_users for delete
  using (auth.uid() = blocked_by);

-- Add index for better performance
create index if not exists idx_blocked_users_blocked_by on blocked_users(blocked_by);
create index if not exists idx_blocked_users_blocked_user on blocked_users(blocked_user);